### ISSUE TITLE
setvcp command does not parse a feature code as hexadecimal

### ISSUE THREAD

**Issue by chiguri** [arcnmx/ddcset-rs#3]
When we get the value of brightness, we write
> ddcset getvcp 10,

(0x10 is the feature code for brightness)
but when we set the value as 70, we should write
> ddcset setvcp 16 70

rather than
> ddcset setvcp 10 70.

Help message says that it would be parsed as hexadecimal, but actually it is parsed as decimal.

**Comment by arcnmx** [comment]
Thanks for finding and reporting that inconsistency!
