### ISSUE TITLE
Getting error "Failed to set feature: DDC/CI error: Expected DDC/CI length bit" while setting display brightness, but the brightness did change

### ISSUE THREAD

**Issue by mickdekkers** [arcnmx/ddcset-rs#5]
Hello! First of all, thanks for making this. I've been looking for something that would let me control my monitor brightness through the command line so I can integrate it into my home automation system. `ddcset` looks perfect for this, and as a bonus it's written in Rust which I'm currently learning 👌 

I've got an Acer Predator X34 monitor attached to my Windows 10 PC. I tried using `ddcset` to adjust the brightness of the monitor. This worked great — the brightness changed to the value I set it to — except `ddcset` logged an error while doing so.

The following is the output of several `ddcset` commands to provide some context.

`ddcset detect` output:

```
Display on winapi:
        ID: Generic PnP Monitor
        MCCS: 2.2
Display on nvapi:
        ID: TU104-A/2147881091:Lvds
        Manufacturer ID: ACR
        Model: Acer X34
        Serial: #(omitted)
        MCCS: 2.2
```

`ddcset -b nvapi capabilities` output:

```
Display on nvapi:
        ID: TU104-A/2147881091:Lvds
        Feature 0x02: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x03: Unknown
                Access: ReadWrite
                Type: Non-Continuous
                        0x01: Unknown
        Feature 0x04: Restore Factory Defaults
                Access: WriteOnly
                Group: Preset Operations
                Type: Non-Continuous
                Restore all factory presets including luminance / contrast, geometry, color and TV defaults.
        Feature 0x05: Restore Factory Luminance / Contrast Defaults
                Access: WriteOnly
                Group: Preset Operations
                Type: Non-Continuous
                Restores factory defaults for luminance and contrast adjustments.
        Feature 0x08: Restore Factory Color Defaults
                Access: WriteOnly
                Group: Preset Operations
                Type: Non-Continuous
                Restore factory defaults for color settings.
        Feature 0x10: Brightness
                Access: ReadWrite
                Type: Continuous
        Feature 0x12: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x14: Unknown
                Access: ReadWrite
                Type: Non-Continuous
                        0x03: Unknown
                        0x05: Unknown
                        0x09: Unknown
                        0x0b: Unknown
        Feature 0x16: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x18: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x1a: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x2e: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x52: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x59: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x5a: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x5b: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x5c: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x5d: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x5e: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0x72: Unknown
                Access: ReadWrite
                Type: Non-Continuous
                        0x00: Unknown
                        0x78: Unknown
                        0xff: Unknown
        Feature 0x8a: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0xac: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0xae: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0xb6: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0xc0: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0xc8: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0xc9: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0xca: Unknown
                Access: ReadWrite
                Type: Continuous
        Feature 0xdf: VCP Version
                Access: ReadOnly
                Required
                Group: Display Control
                Type: Non-Continuous
                Defines the version number of the MCCS standard recognized by the display.
```

`ddcset -b nvapi getvcp 10` (brightness) output:
```
Display on nvapi:
        ID: TU104-A/2147881091:Lvds
        Feature 0x10 = 12 / 100
```

`ddcset -b nvapi setvcp 10 14` (brightness) output:
```
Display on nvapi:
        ID: TU104-A/2147881091:Lvds
ERROR 2020-01-06T18:39:55Z: ddcset: Failed to set feature: DDC/CI error: Expected DDC/CI length bit
```

Googling the last part of the error message lead me to these lines of the source code of `ddc-i2c`:
https://github.com/arcnmx/ddc-i2c-rs/blob/cc7268f36ec262aec1bc13a0813376ca4cffaf92/src/lib.rs#L178-L181
That includes a TODO which states:
> // TODO: apparently sometimes this isn't true?

I'd like to help debug this issue, though I'm still fairly new to Rust (just finished "The Book"). Please let me know what I can do to help :)

---

For the sake of completeness: Although I'm using Windows 10, I've got my Rust development environment set up in Windows Subsystem for Linux (running Ubuntu 18.04), so I cross-compiled `ddcset` using the `x86_64-pc-windows-gnu` target.

Specifically, I used this command:
`cargo install --target x86_64-pc-windows-gnu --root . --git https://github.com/arcnmx/ddcset-rs.git`

Then copied the resulting `./bin/ddcset.exe` to my bin folder in Windows.

This is my `~/.cargo/config`:
```
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
ar = "x86_64-w64-mingw32-gcc-ar"
```

Compiled with `rustc 1.42.0-nightly (0de96d37f 2019-12-19)`

**Comment by arcnmx** [comment]
Hi, thanks for the detailed report! I'm away and don't have time at the moment to dig into this but just wanted to leave a note to help guide you in the right direction if you do wish to debug a bit:

- You can use [./.cargo/config](https://doc.rust-lang.org/cargo/reference/config.html#configuration-keys) path overrides to get ddcset compiled with a working copy of ddc-i2c that you can edit and mess with.
- Try deleting the linked `if` check and see if the checksum and rest of it still works properly?
- It's maybe worth trying out the winapi backend instead? I don't remember the functional state of that driver though, I've put more time and focus into the i2c based ones for various reasons.

Judging by the `TODO` note it seems like an issue with the assumptions made there regarding the response data sent over ddc after the command. I'll need to consult the spec to remember why that check is there and figure out which conditions under which it may not be correct.

**Comment by mickdekkers** [comment]
Hi, sorry for not replying sooner! I'm afraid the notification got buried in my GitHub inbox 😅
Thanks for your reply and for taking the time to fix this! I just tested this using the latest commit and `rustc 1.45.1 (c367798cf 2020-07-26)`. I can confirm it's fixed and works flawlessly now! 😄
